server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.196.53.11:3306/PACKAHE_MANAGE?characterEncoding=utf-8
    username: root
    password: yh0769

